### ISSUE TITLE
Demo QR code?

### ISSUE THREAD

**Issue by marcel-bluestone** [YC/another_authenticator#5]
Is there a demo QR code that can be used to test the library? I don't understand, which information needs to be incorporated and where I can create appropriate codes to be scanned for using the lib.

I'd appreciate an example. Thanks

**Comment by YC** [comment]
Please note that this app is not really a library. 
It uses `barcode_scan` to scan the QR and [parses](https://github.com/YC/another_authenticator/blob/master/lib/totp/totp_uri.dart) the Uri that is extracted from the QR. 
First result of 2FA QR generator from Google: https://stefansundin.github.io/2fa-qr/
Perhaps you can describe what you'd like to achieve.

**Comment by marcel-bluestone** [comment]
Sorry YC for not getting back earlier. I managed to create a barcode with https://stefansundin.github.io/2fa-qr/ and scan it. Then I understood what the example app was supposed to do.

Thanks.
